settings:
  name: "Product Name"
  search: 
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
  # harmony_enabled: true

sidebar: 
  entries:
  - title: #repeat title of family page
    url: /index.html
