settings:
  name: NetApp Console storage management
  search: console-relnotes,console-setup-admin,storage-management-cloud-volumes-ontap,storage-management-ontap-onprem,storage-management-azure-netapp-files,storage-management-fsx-ontap,data-services-backup-recovery,data-services-copy-sync,data-services-data-classification,data-services-cloud-tiering,data-services-replication,console-automation,cloud-volumes-ontap-relnotes,storage-management-storagegrid,storage-management-e-series,storage-management-s3-storage,console-lifecycle-planning,console-licenses-subscriptions,storage-management-blob-storage,data-services-volume-caching,data-services-disaster-recovery,storage-management-blob-storage,storage-management-google-cloud-storage,console-automation,data-services-ransomware-resilience,console-software-updates,console-alerts,workload-setup-admin,workload-fsx-ontap,workload-databases,workload-genai,workload-vmware
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: true
    lipi_enabled: false
sidebar:
  entries:
    - title: NetApp Console storage management docs
      url: /index.html
