settings:
  name: NetApp Console storage management
  #search: console-relnotes,console-family,storage-management-cloud-volumes-ontap,storage-management-ontap-onprem,storage-management-azure-netapp-files,storage-management-fsx-ontap,cloud-volumes-ontap-relnotes, storage-management-storagegrid,storage-management-e-series,storage-management-s3-storage,storage-management-blob-storage,storage-management-google-cloud-storage, storage-management-google-cloud-netapp-volumes,data-services-family, keystone-staas
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: true
    lipi_enabled: false
sidebar:
  entries:
    - title: NetApp Console storage management docs
      url: /index.html
